namespace Janglin.Glassdoor.Client.Classic
{
	public enum JobCategory
	{
		None = 0,
		AccountingFinance = 1,
		Administrative = 2,
		Analyst = 3,
		ArchitectureDrafting = 4,
		ArtDesignEntertainment = 5,
		BankingLoanInsurance = 6,
		BeautyWellness = 7,
		BusinessDevelopmentConsulting = 8,
		Education = 9,
		EngineeringNonSoftware = 10,
		FacilitiesGeneralLabor = 11,
		Hospitality = 12,
		HumanResources = 13,
		InstallationMaintenanceRepair = 14,
		Legal = 15,
		ManufacturingProductionConstruction = 16,
		MarketingAdvertisingPR = 17,
		MedicalHealthcare = 18,
		NonProfitVolunteering = 19,
		ProductProjectManagement = 20,
		RealEstate = 21,
		RestaurantFoodServices = 22,
		Retail = 23,
		SalesCustomerCare = 24,
		ScienceResearch = 25,
		SecurityLawEnforcement = 26,
		SeniorManagement = 27,
		SkilledTrade = 28,
		SoftwareDevelopmentIT = 29,
		SportsFitness = 30,
		TravelTransportation = 31,
		WritingEditingPublishing = 32,
		Other = 33,
	}
}